#!/bin/sh
(cd host/lib && make)
(cd host/apps && make)
(mkdir -p firmware/src/bld18 && cd firmware/src/bld18 && make -f ../avnet/Makefile VPATH=../avnet TARGET_BOARD=0x0018 usrp_main.ihx)
(mkdir -p firmware/src/bld19 && cd firmware/src/bld19 && make -f ../avnet/Makefile VPATH=../avnet TARGET_BOARD=0x0019 usrp_main.ihx)
(mkdir -p firmware/src/bld1a && cd firmware/src/bld1a && make -f ../avnet/Makefile VPATH=../avnet TARGET_BOARD=0x001a usrp_main.ihx)
