#!/bin/sh
# (tested with bash and dash)
# see burn_eeprom for more info
set -e
I2C_ADDR=0x51
which=${1:-0}
usrper -w $which i2c_write $I2C_ADDR 00f8
hexs=`usrper -w $which i2c_read $I2C_ADDR 8`
perl -e '$s="'$hexs'"; print pack("H*",$s), "\n";'
